#ifndef AM335X_DDR_H
#define AM335X_DDR_H

/* EMIF */
#define EMIF_BASE                   0x4C000000
#define EMIF_STATUS                 (EMIF_BASE + 0x04)
#define EMIF_SDRAM_CONFIG           (EMIF_BASE + 0x08)
#define EMIF_SDRAM_CONFIG2          (EMIF_BASE + 0x0C)
#define EMIF_SDRAM_REF_CTRL         (EMIF_BASE + 0x10)
#define EMIF_SDRAM_REF_CTRL_SHDW    (EMIF_BASE + 0x14)
#define EMIF_SDRAM_TIM_1            (EMIF_BASE + 0x18)
#define EMIF_SDRAM_TIM_2            (EMIF_BASE + 0x20)
#define EMIF_SDRAM_TIM_3            (EMIF_BASE + 0x28)
#define EMIF_PWR_MGMT_CTRL          (EMIF_BASE + 0x38)
#define EMIF_DDR_PHY_CTRL_1         (EMIF_BASE + 0xE4)
#define EMIF_DDR_PHY_CTRL_2         (EMIF_BASE + 0xEC)

/* DDR PHY (via Control Module) */
#define CONTROL_MODULE_BASE         0x44E10000

#define DDR_CMD0_IOCTRL             (CONTROL_MODULE_BASE + 0x1404)
#define DDR_CMD1_IOCTRL             (CONTROL_MODULE_BASE + 0x1408)
#define DDR_CMD2_IOCTRL             (CONTROL_MODULE_BASE + 0x140C)
#define DDR_DATA0_IOCTRL            (CONTROL_MODULE_BASE + 0x1440)
#define DDR_DATA1_IOCTRL            (CONTROL_MODULE_BASE + 0x1444)

#define DDR_CMD0_SLAVE_RATIO_0      (CONTROL_MODULE_BASE + 0x0C1C)
#define DDR_CMD0_INVERT_CLKOUT_0    (CONTROL_MODULE_BASE + 0x0C2C)
#define DDR_CMD1_SLAVE_RATIO_0      (CONTROL_MODULE_BASE + 0x0C50)
#define DDR_CMD1_INVERT_CLKOUT_0    (CONTROL_MODULE_BASE + 0x0C60)
#define DDR_CMD2_SLAVE_RATIO_0      (CONTROL_MODULE_BASE + 0x0C84)
#define DDR_CMD2_INVERT_CLKOUT_0    (CONTROL_MODULE_BASE + 0x0C94)

#define DDR_DATA0_RD_DQS_SLAVE_RATIO_0    (CONTROL_MODULE_BASE + 0x0CC8)
#define DDR_DATA0_WR_DQS_SLAVE_RATIO_0    (CONTROL_MODULE_BASE + 0x0CD4)
#define DDR_DATA0_FIFO_WE_SLAVE_RATIO_0   (CONTROL_MODULE_BASE + 0x0CD8)
#define DDR_DATA0_WR_DATA_SLAVE_RATIO_0   (CONTROL_MODULE_BASE + 0x0CDC)
#define DDR_DATA0_GATE_LEVEL_INIT_RATIO_0 (CONTROL_MODULE_BASE + 0x0CE4)

#define DDR_DATA1_RD_DQS_SLAVE_RATIO_0    (CONTROL_MODULE_BASE + 0x0D0C)
#define DDR_DATA1_WR_DQS_SLAVE_RATIO_0    (CONTROL_MODULE_BASE + 0x0D18)
#define DDR_DATA1_FIFO_WE_SLAVE_RATIO_0   (CONTROL_MODULE_BASE + 0x0D1C)
#define DDR_DATA1_WR_DATA_SLAVE_RATIO_0   (CONTROL_MODULE_BASE + 0x0D20)
#define DDR_DATA1_GATE_LEVEL_INIT_RATIO_0 (CONTROL_MODULE_BASE + 0x0D28)

#define DDR_IO_CTRL     (CONTROL_MODULE_BASE + 0xE04)
#define VTP_CTRL        (CONTROL_MODULE_BASE + 0xE0C)
#define DDR_CKE_CTRL    (CONTROL_MODULE_BASE + 0x131C)

#endif /* AM335X_DDR_H */
